kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pv-claim
spec:
  storageClassName: longhorn
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: longhornio/dbench:latest
        imagePullPolicy: Always
        securityContext:
          # Need this for fio be able to invalid the cache
          privileged: true
        env:
          #- name: DBENCH_MOUNTPOINT
          #  value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          - name: FIO_SIZE
            value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        #volumeMounts:
        #- name: dbench-pv
        #  mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-pv-claim
  backoffLimit: 4
